version: '3.8'

services:
  mcp-server:
    image: mcp/server:latest
    container_name: mcp-server
    ports:
      - "8811:8811"
    volumes:
      - ./mcp_data:/data
      - ./your_mcp_modules:/mcp_modules
      - ./init_mcp.sh:/docker-entrypoint-init.d/init_mcp.sh
      - ./certs:/certs
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:8811/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - mcp_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mcp_net

networks:
  mcp_net:
    driver: bridge