global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mcp_server'
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['mcp-server:8811']