# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: features.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'features.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65\x61tures.proto\x12\x07trading\"j\n\nFeatureSet\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65ma_fast\x18\x02 \x01(\x01\x12\x10\n\x08\x65ma_slow\x18\x03 \x01(\x01\x12\x12\n\nvolatility\x18\x04 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"e\n\x06Signal\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x11\n\texpiry_ms\x18\x04 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEATURESET']._serialized_start=27
  _globals['_FEATURESET']._serialized_end=133
  _globals['_SIGNAL']._serialized_start=135
  _globals['_SIGNAL']._serialized_end=236
# @@protoc_insertion_point(module_scope)
